// <auto-generated />
using Kpoper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kpoper.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240923172738_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Kpoper.Entities.Idol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Full Name");

                    b.Property<int>("IdolLinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdolSex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Idols");
                });
#pragma warning restore 612, 618
        }
    }
}
